# Generated by Django 5.2.5 on 2025-09-03 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='restrictions',
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='m', max_digits=4)),
                ('historico_medico', models.TextField(blank=True)),
                ('restricoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='contas.aluno')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-data'],
            },
        ),
    ]
