# Generated by Django 5.2.5 on 2025-11-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/photos/'),
        ),
        migrations.AddField(
            model_name='personal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personals/photos/'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='proprietarios/photos/'),
        ),
    ]
