# Generated by Django 5.2.5 on 2025-08-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='type_user',
            field=models.CharField(default='ALUNO', max_length=8),
        ),
    ]
