# Generated by Django 5.2.5 on 2025-08-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alunos_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='cref',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
