# Generated by Django 5.2.8 on 2025-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_aluno_photo_personal_photo_proprietario_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='dia',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='treino',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
