# Generated by Django 5.2.8 on 2025-11-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_treino_dia_treino_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
