# Generated by Django 5.2.5 on 2025-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alunos_cref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cref',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
