# Generated by Django 5.2.8 on 2025-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_aluno_bairro_aluno_cep_aluno_numero_aluno_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
